name: Build

on:
    workflow_dispatch: {}

    push:
        branches:
            - main

    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6.0.2

            - name: Setup Go
              uses: actions/setup-go@v6.4.0
              with:
                  go-version-file: ./go.mod

            - name: Build
              run: make build
