name: build

on:
    workflow_dispatch: {}

    push:
        branches:
            - main

    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2

            - name: Setup Go
              uses: actions/setup-go@v5.5.0
              with:
                  go-version-file: ./go.mod

            - name: Verify Go Modules
              run: go mod verify

            - name: Build
              run: make build
